### ISSUE TITLE
model statistics are wrong

### ISSUE THREAD

**Issue by nih23** [nish03/Intraoperative-neural-imaging-#8]
You are computing the model's residual in line 41 of ThermalImagingAnalysis.py. However, this residual is computed using the noMRF fit. You probably need to compute the model fit using the re-computed alpha (where do you compute it?) as well as the regularized Spline coefficients (beta_mrf in line 37)

**Comment by nish03** [comment]
I used the below code before in accordance with our discussion about refit of parametric component but it was not giving me desired output:



beta = GTGpDsG.dot(S2)  
beta_mrf = pm.pixel_mrf_model(num_knots,num_clusters,beta,S2,G,noPixels) 
beta_nonparam = beta_mrf[noFixedComponents:]
Y_hat = B.transpose().dot(beta_nonparam)
XtX = X.transpose().dot(X)
XtXinvXt = linalg.lstsq(XtX, X.transpose())[0]   #linalg.lstsq since X is a singular matrix
alpha_fit = XtXinvXt.transpose().dot(S2 - Y_hat)
beta_fit = np.concatenate([alpha_fit, beta_nonparam])
#residuals
seqF = G.dot(beta_fit)
eGlobal = S2 - seqF
